# server port : 9099
server:
  port: 9099

# Spring Setting
spring:
  application:
    name: SpringGroupBB

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

    thymeleaf:
      cache: false

  # DataBase Setting(Datasource)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springgroupbb
    username: root
    password: 1234

  # JPA Setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # create, update, none, create-drop, validate...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false # SQL Log Display Setting
    properties:
      hibernate:
        format_sql: true # SQL Log Display Setting
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Security User Password Setting (Security Login Info Setting)
  security:
    user:
      name: vocalyui123@gmail.com
      password: 1234

  # File Upload Setting
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# Log Information Setting
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # SQL Log Display Setting